# Introduction

In this lab, we are going to leverage a process known as [`oc cluster up`](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md). `oc cluster up` leverages the local docker daemon and enables us to quickly stand up a local OpenShift Container Platform to start our evaluation. The key result of `oc cluster up` is a reliable, reproducible OpenShift environment to iterate on.

We will also build out resourses needed for later labs:
A container registry, as well as a forntend application and database docker container which will later be imported into OpenShift.

Expected completion: 5-10 minutes

## Find your AWS Instance
This lab is designed to accommodate many students. As a result, each student will be given a VM running on AWS. The naming convention for the lab VMs is:

**student-\<number\>**.openshift.awsworkshop.io

You will be assigned a number by the instructor.

Step 1:: Retrieve the key from the Download links here

If you are running this workhshop in the ASIA:

----
[SSH Private Key - PEM ](https://s3-us-west-2.amazonaws.com/redhat-workshops/keys/apac-workshops.pem)
[SSH Private Key - PPK ](https://s3-us-west-2.amazonaws.com/redhat-workshops/keys/apac-workshops.ppk)
----

If You are running this workshop in US:

----
[SSH Private Key - PEM ](https://s3-us-west-2.amazonaws.com/redhat-workshops/keys/ocp-lab.pem)
[SSH Private Key - PPK ](https://s3-us-west-2.amazonaws.com/redhat-workshops/keys/ocp-lab.ppk)
----


You can now _SSH_ into the instances by downloading the `.PEM` or `.PPK` file to your local machine and change the permissions of the file to `400` if you are using `Mac OSX` or `Linux`.

Linux command to download the key file and change permissions.
----
curl -kLO "https://s3-us-west-2.amazonaws.com/redhat-workshops/keys/ocp-lab.pem"
curl -kLO "https://s3-us-west-2.amazonaws.com/redhat-workshops/keys/apac-workshops.pem"
chmod 400 ocp-lab.pem
chmod 400 apac-workshops.pem
----

If you are using `Windows` and `Putty`, download the PPK file and log in using `Putty`

Important!: The Linux user to log in with is `ec2-user`

## Connecting to your AWS Instance
This lab should be performed on **YOUR ASSIGNED AWS INSTANCE** as `ec2-user` unless otherwise instructed.

Step 2:: Connect to the instance:
If running the lab in US:
----
$ ssh -i ocp-lab.pem ec2-user@student-<number>.openshift.awsworkshop.io
----
If running the lab in the ASIA:
----
$ ssh -i apac-workshops.pem ec2-user@student-<number>.openshift.awsworkshop.io
----


**NOTE**: For Windows users you will have to use a terminal like [PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) to SSH using the private key.

Once installed, use the following instructions to SSH to your VM instance: [http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html).


## Getting Set Up
For the sake of time, some of the required setup has already been taken care of on your AWS VM. For future reference though, the easiest way to get started is to head over to the OpenShift Origin repo on github and follow the "[Getting Started](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md)" instructions. The instructions cover getting started on Windows, MacOS, and Linux.

Since some of these labs will have long running processes, it is recommended to use something like `tmux` or `screen` in case you lose your connection at some point so you can reconnect:

Step 3:: Install and run screen:
----
$ sudo yum -y install screen
$ screen
----

In case you get disconnected use `screen -x` or `tmux attach` to reattach once you reestablish ssh connectivity. If you are unfamiliar with screen, check out this [quick tutorial](https://www.mattcutts.com/blog/a-quick-tutorial-on-screen/). For tmux here is a [quick tutorial](https://fedoramagazine.org/use-tmux-more-powerful-terminal/).

All that's left to do is run OpenShift by executing the `start-oc.sh` script in your home directory. First, let's take a look at what this script is doing, it's grabbing AWS instance metadata so that it can configure OpenShift to start up properly on AWS:

Step 4:: (OPTIONAL) Inspect script to bring up the cluster:
----
$ cat ~/start-oc.sh
----

Step 5:: Now, let's start our local, containerized OpenShift environment:
----
$ ~/start-oc.sh
----

The resulting output should be something of this nature
----
Using nsenter mounter for OpenShift volumes
Using 127.0.0.1 as the server IP
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.9.14 ...
OpenShift server started.

The server is accessible via web console at:
    https://<public hostname>:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin
----

You should get a lot of feedback about the launch of OpenShift. As long as you don't get any errors you are in good shape.

OK, so now that OpenShift is available, let's ask for a cluster status & take a look at our running containers.

Step 6:: (OPTIONAL) Check the Cluster version and state.
----
$ oc version
$ oc cluster status
----

As noted before, `oc cluster up` leverages docker for running
OpenShift. You can see that by checking out the containers and
images that are managed by docker:

Step 7:: Inspect docker process:
----
$ docker ps
$ docker images
----

As you can see there are several docker containers running, these are all the infrastructure components of OpenShift.
As application workloads are run in OpenShift further containers will be launched.

We can also check out the OpenShift console. Open a browser and navigate to `https://<public-hostname>:8443`. Be sure to use http*s* otherwise you will get weird web page. Once it loads (and you bypass the certificate errors), you can log in to the console using the default developer username (use any password).

## Lab Materials

Step 7:: Clone the lab repository from github:

----
$ cd ~/
$ git clone https://github.com/rniksch/openshift-on-aws.git
----

## OpenShift Container Platform

What is OpenShift? OpenShift, which you may remember as a "[PaaS](https://en.wikipedia.org/wiki/Platform_as_a_service)" to build applications on, has evolved into a complete container platform based on Kubernetes. If you remember the "[DIY Cartridges](https://github.com/openshift/origin-server/blob/master/documentation/oo_cartridge_guide.adoc#diy)" from older versions of Openshift, essentially, OpenShift v3 has expanded the functionality to provide complete containers. With OpenShift, you can build from a platform, build from scratch, or anything else you can do in a container, and still get the complete lifecycle automation you loved in the older versions.

Before we get our hands dirty we will run a setup process which will build out some basic docker application workloads and pushh these to a local container registry. 

Step 8:: Run the setup
----
cd ~/openshift-on-aws/labs/lab0
chmod 755 setup.sh
./setup.sh
----

This will use an ansible playbook to create a local container registry on port 5000 which we will later interact with.


You are now ready to move on to the next lab.
