# Application Modernization

In this lab, we are going to build upon the previous labs and leverage what we have learned to utilize the [AWS Service Broker](https://github.com/awslabs/aws-servicebroker) to provision AWS RDS database instance, and migrate the wordpress container application deployed in an earlier lab to use this as a Database source.

Expected completion: 20 - 35 minutes

Many customers are taking application workloads as they exist on premises and lift and shift these through OpenShift to their AWS environments.
Once the workloads are here we see modernization through layers of the appliction being replaces with native AWS services. These commonly include RDS, DynamoDB, SNS, SQS, etc.



Step 1:: Deploy a Maria DB RDS instance using the AWS Servcie Broker.
----
From the service catalog select RDS MariaDB.
Select the develeopment plan.
Select production from the add to project drop down.
Type in 0.0.0.0/0 under access CIDR.
Under VPC ID add vpc-0f2cc5214df5e3664.
Select Next
Select do not bind at this time.
Select create.
----

Step 2:: Bind the RDS instance to the workpress application.
This will Store the connection details such as endpoint username and passwork in the OpenShift Secret store. Applications can assess this info without exposing it to humans.
----
Navigate back to the `Overview` tab in the `OpenShift Console` for the production project.
Under provisioned services select RDS mariaDB.
Select create binding.
Select Bind.
Select view Secret.
Take note of the ID, it will look something like dh-rds-xxxx-credentials-xxxx.
Select add to application.
From the Add this secret to application: drop down select wordpress.
----

Open Shift will detect changes to the application pods and restart the application pods.
The credenctials for the RDS will be available to the wordpress application as evn variables.

However the wordpress will at this stage still be using its existing config using the mariaDB container DB we imported in an earlier lab.

Step 3:: Update the wordpress config mapping to consume the env variables provided by the secret
----
Navigate back to the `Overview` tab in the `OpenShift Console` for the production project.
Select Wordpress
Select envrionment
Click on Add Value from Config Map or Secret.
add *DB_ENV_DBNAME* to the Name field
Select the secret created above from the select resource drop down.
Select *DB_NAME* from the select key drop down.

Click on Add Value from Config Map or Secret.
add *DB_ENV_DBUSER*  to the Name field
Select the secret created above from the select resource drop down.
Select *MASTER_USERNAME* from the select key drop down.

Click on Add Value from Config Map or Secret.
add *DB_ENV_DBPASS*  to the Name field
Select the secret created above from the select resource drop down.
Select *MASTER_PASSWORD* from the select key drop down.

Click on Add Value from Config Map or Secret.
add  *MARIADB_SERVICE_HOST* to the Name field
Select the secret created above from the select resource drop down.
Select *ENDPOINT_ADDRESS* from the select key drop down.

Click on Add Value from Config Map or Secret.
add *MARIADB_SERVICE_PORT* to the Name field
Select the secret created above from the select resource drop down.
Select *PORT* from the select key drop down.

Delete the top 3 mappings which refer to the mariaDB container.
Click on Save
Click on Deploy
----

Your pods should now automatically restart.

Step 4:: remove the mariadb container.
----
Navigate back to the `Overview` tab in the `OpenShift Console` for the production project.
Select Mariadb
select actions
Select Delete.
----

Once this container has been removed go back and verify that wordpress is communicating with the RDS instance provisioned by the broker.

It is important to note that any data on the existing data base should be migrated to the new RDS instance in many cases. SHould this be a requirement Amazon data migration  services can be used to migtrate the database content before updating the config mapping.


### Verify
Go back to the sample webpage that gave you errors earlier and refresh the page. You should now see the app returning request IDs


